### ISSUE TITLE
Issue: Fix provinces names.

### ISSUE THREAD

**Issue by Czubaduba** [KarlHabsburg/Megameme#15]
Change names to proper ones for the following provinces
#3246
#2632
#2591

**Comment by west3436** [comment]
please list the proper names

**Comment by Czubaduba** [comment]
Jan Mayen for Jan Mayen
Eirik Raudes Land for eastern greenlandic province
Jakobshavn for western greenlandic province.

Dunno which number is which because I turned off the game heh.

**Comment by west3436** [comment]
Closed in #19.

**Comment by west3436** [comment]
Closed in #19.
