### ISSUE TITLE
Issue: Fix Wakanda not carrying over from eu4

### ISSUE THREAD

**Issue by BomberBro** [KarlHabsburg/Megameme#22]
BLACK PANTHER

                         

                          
                           Written by 

                 Ryan Coogler & Joe Robert Cole

          EXT. DEEP SPACE

          A dark screen is lit up by twinkling stars .

                          SON
           Baba?

                          FATHER
           Yes, my son?

                          SON
           Tell me a story .

                          FATHER
           Which one?

                          SON
           The story of home .
          A meteorite drifts into frame , heading towards tiny Earth off
          in the distance.

                          FATHER
           Millions of years ago , a meteorite
           made of vibranium, the strongest
           substance in the universe struck
           the continent of Africa affecting
           the plant life around it.

          The meteorite hits Africa and we see plant life and animals
          affected by vibranium.

                          FATHER (CONT'D)
           And when the time of man came , five
           tribes settled on it and called it
           Wakanda. The tribes lived in
           constant war with each other until
           a warrior shaman received a vision
           from the Panther goddess Bast who
           led him to the Heart Shaped Herb, a
           plant that granted him super human
           strength , speed, and instincts.

          A visual representation of the five tribes emerges as hands
          from the sand animation, and we see them unite , and then
          break apart as conflict arises . Bashenga rises above the
          conflict and eats the Heart Shaped Herb, proceeding to unite
          the tribes .

                          FATHER (CONT'D)
           The warrior became King and the
           first Black Panther , the protector
           of Wakanda .

**Comment by west3436** [comment]
feature
