### ISSUE TITLE
Manifest Destiny should give more cores to the USA

### ISSUE THREAD

**Issue by JamesWBigmac** [KarlHabsburg/Megameme#46]
Currently the Manifest destiny decision for America gives cores on the historical Mexican cession area, I believe this should be expanded to include some Scandinavian territory as well.

**Comment by Thomas-LeCoent** [comment]
Maybe it should be changed to only include provinces in this area like we discussed https://media.discordapp.net/attachments/780926634546561044/809141254117261382/20210210141754_1.jpg ?

**Comment by Thomas-LeCoent** [comment]
With a second event/decision later to annex Cuba and such
