### ISSUE TITLE
African Province Liferating/Localization

### ISSUE THREAD

**Issue by Thundercat69** [KarlHabsburg/Megameme#49]
I am monkey brain no idea how to use github but here's a list of provinces that have either 1 or 3 liferating and are thus uncolonizable
Mayumbe - 1974 
Harper - 1888
Monrovia - 1887
Ibo - 2063
Tete - 2054
Sena - 2053
Harare - 2068
Umtali(in game name) -2070 - Mutare (province/africa txt file name)
Chiconono(in game name) - 2581 - Mataka (province/africa txt file name)
Baraka(In game name) - 1972 - Libreville (province/africa txt file name)

Also something is wrong with Mozambique, shows 35 liferating in game but if you hover over it, it will tell you that you aren't able to colonize it as it has 1 liferating after clicking around the map a few times

as well there are a lot of 5 liferating provinces that HPM creates, afaik you can't colonize those with existing techs and they are instead given out via hpm decisions/events which i'm not sure exist

currently investigating further

**Comment by west3436** [comment]
Thunder sent me the files to close this so I'll make a PR to do so later today :pepecomfy:
