### ISSUE TITLE
USA issues

### ISSUE THREAD

**Issue by danieliocean** [KarlHabsburg/Megameme#87]
Issues:
- No option to change government form or tag when you become independent
- Colonies don't change name when they become states
- Adjective stays "Thirteen Colonies" after you become USA

Suggestions:
- Should be a more streamlined way to get cores from Vinland (you have to for Kalamar to release it which puts it in your sphere)
- Make a way for puppets that you liberate in NA to petition for statehood (like Florida)

**Comment by west3436** [comment]
- Fixing the first bullet with an event.
- Next two items are already fixed in the latest version of the mod.
- Working on a Manifest Destiny event which will do bullet 4 per #46.
- Last item is way OP since you could just inhale Vinland so no!
